DOR fixes
raror3/Jarvis4Ops pull request #38
Opened 2017-03-23 14:41 UTC by UmangSapient

Few changes have been done in below 14 files for DOR alert fix.
Please review.

src/main/java/org/jarvis4ops/bean/ActiveSprintDetails.java
 src/main/java/org/jarvis4ops/bean/ActiveSprintResponse.java
 src/main/java/org/jarvis4ops/bean/DorParameters.java
 src/main/java/org/jarvis4ops/bean/Fields.java
 src/main/java/org/jarvis4ops/configurations/Configurations.java
 src/main/java/org/jarvis4ops/configurations/JiraConstants.java
 src/main/java/org/jarvis4ops/configurations/SlackMessagingConstants.java
 src/main/java/org/jarvis4ops/controller/JiraController.java
 src/main/java/org/jarvis4ops/controller/SlachController.java
 src/main/java/org/jarvis4ops/helper/DorDodIssuesHelper.java
 src/main/java/org/jarvis4ops/helper/JiraHelper.java
 src/main/resources/jiraConstants.properties
 src/main/resources/slackMessaging.properties

2017-03-25 10:20 UTC, raror3 requested changes
Request you to please help action on the review comments - so that we can make the code more cleaner @UmangSapient

2017-03-25 10:20 UTC, raror3 commented on src/main/java/org/jarvis4ops/bean/ActiveSprintDetails.java
> +public class ActiveSprintDetails {
As its a bean - you can rename it to SprintDetailBean (will then be reusable with the name)

2017-03-25 10:20 UTC, raror3 commented on src/main/java/org/jarvis4ops/bean/ActiveSprintResponse.java
> +public class ActiveSprintResponse {
I think renaming it to JiraValuesResponseBean or like might make it more eligible for re-using.
what do you think?

2017-03-25 10:20 UTC, raror3 commented on src/main/java/org/jarvis4ops/bean/DorParameters.java
>  	public String toString() {
You can remove this toString method overall - if you are not using it anywhere (a suggestion)

2017-03-25 10:20 UTC, raror3 commented on src/main/java/org/jarvis4ops/helper/DorDodIssuesHelper.java
> +import ch.qos.logback.core.net.SyslogOutputStream;
Any specific need to use this import statement please?

2017-03-25 10:20 UTC, raror3 commented on src/main/java/org/jarvis4ops/helper/DorDodIssuesHelper.java
> +import org.springframework.boot.autoconfigure.jdbc.metadata.TomcatDataSourcePoolMetadata;
Any specific need to use this import statement please?

2017-03-25 11:05 UTC, UmangSapient commented on src/main/java/org/jarvis4ops/bean/ActiveSprintDetails.java
> +public class ActiveSprintDetails {
I have changed it's name to SprintDetailBean

2017-03-25 11:06 UTC, UmangSapient commented on src/main/java/org/jarvis4ops/bean/ActiveSprintResponse.java
> +public class ActiveSprintResponse {
Changed its name to JiraActiveSprintResponseBean

2017-03-25 11:10 UTC, UmangSapient commented on src/main/java/org/jarvis4ops/bean/DorParameters.java
>  	public String toString() {
I have removed this unused toString method

2017-03-25 11:11 UTC, UmangSapient commented on src/main/java/org/jarvis4ops/helper/DorDodIssuesHelper.java
> +import org.springframework.boot.autoconfigure.jdbc.metadata.TomcatDataSourcePoolMetadata;
Removed unused import.

2017-03-25 11:11 UTC, UmangSapient commented on src/main/java/org/jarvis4ops/helper/DorDodIssuesHelper.java
> +import ch.qos.logback.core.net.SyslogOutputStream;
Removed unused import.

2017-03-25 11:20 UTC, UmangSapient commented
@raror3 I have incorporated review comments , additionally removed few more unused imports . Please review.

2017-03-26 16:01 UTC, raror3 approved these changes

2017-03-26 16:01 UTC, merged